webdino/gitfab2

app/assets/stylesheets/projects/index.css.scss
app/views/projects/index.html.slim

アイコンサイズを統一しました。
縦横比が1:1でない画像は短い辺に合わせて中央を表示します。

closed #923 fix image size of users/icon

---

app/assets/javascripts/card.js.coffee
app/assets/javascripts/project_form.js.coffee

Feature request #1147 
Reason:
YouTube gives share URL of videos as “https://youtu.be/{id}” .
Valid URL
https://youtu.be/QmjSb48yVO8
http://youtube.com/watch?v=QmjSb48yVO8
https://www.youtube.com/watch?v=QmjSb48yVO8&list=PL7QOwp8NKs9dKqNsgl382n
RXT_iBfzKY6
Invalid URL
https://youtu.be/QmjSb4
https://youtu.be.com/QmjSb48yVO8
ssh://www.youtube.com/watch?v=QmjSb48yVO8

close #1147 Add "youtu.be" URL support.

---

config/clockwork.rb

- 1時間おきのconfig/all-tags.ymlの更新処理において、不正なYAMLが生成され、トップページなどが表示できなくなる問題

タグYAMLが壊れる問題を修正

---

app/uploaders/figure_uploader.rb

奇数ピクセル数のアニメーションGIFを図表として添付した際、再生ボタンを付与する処理でエラーが発生していたのを修正

Fix an error occurring in odd size animation GIF

---

app/views/static_pages/privacy.html.slim

ファブ3Dコンテストの応募受付にfabble.ccを利用するために、プライバシーポリシーの変更が必要になったので、加筆修正を行った。

ファブ3Dコンテスト向けのプライバシーポリシー変更

---

app/views/layouts/_header.html.slim

ヘッダーのティッカーを削除した。23日0時に本番サイトに適用する

ファブ3Dコンテスト終了に伴う変更

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
config/initializers/sentry.rb

#1515 の後
エラートラッキングのためのSentryを導入
`SENTRY_DSN` 環境変数を設定しているとき、Sentryにエラー情報を送信します。

Add sentry-raven

---

Gemfile

activerecord-import は集計で使用するので必要。
なお、Rails6標準のbulk insertは使い勝手が悪いこと、enumへの対応がないなど機能的な不足があるため採用見送りとします。

activerecord-import を production でも使用可能にする

---

app/controllers/projects_controller.rb
app/views/projects/_basic_informations.html.slim
app/views/projects/_popular_projects.html.slim
app/views/projects/_project_comments.html.slim
app/views/projects/_recent_projects.html.slim
app/views/projects/_recipe_cards.html.slim
app/views/projects/_usages.html.slim
app/views/projects/search.html.slim
config/schedule.rb

パーシャルテンプレートが多く、ビューのレンダリングに時間がかかっているので、この対策としてコレクションキャッシュおよびフラグメントキャッシュを導入します。
これによりレンダリングコストの抑制による高速化を期待できます。

Enable caching

---

app/controllers/projects_controller.rb
spec/controllers/projects_controller_spec.rb

フォークリクエスト送信時のパラメータを変更することで次の操作が可能になるセキュリティ上の問題があったのでこれを修正します。
- 自分以外のアカウントに対してフォークを行える不具合
- プライベートプロジェクトをフォークできる不具合
Fork先 `owner_id=xxxxx` に第三者のslugを指定することで、そのユーザー/グループのプロジェクトとしてForkできます。
Fork先がログイン中のユーザー自身か自身が管理しているグループのどちらかであることを確認するようにしました。
Fork先 `owner_id=xxxxx` に第三者のslugを指定することで、そのユーザー/グループのプロジェクトとしてForkできます。
Fork先がログイン中のユーザー自身か自身が管理しているグループのどちらかであることを確認するようにしました。

プロジェクトフォークについてにセキュリティ修正

---

config/deploy.rb
config/deploy/production.rb
config/deploy/staging.rb

Reverts webdino/gitfab2#1522
```bash
$ bundle exec cap production deploy:check
(Backtrace restricted to imported tasks)
cap aborted!
SyntaxError: config/deploy.rb:9: syntax error, unexpected tSYMBEG, expecting do or '{' or '('
+set :whenever_command, -> { "cd #{...
^
Tasks: TOP => production
(See full trace by running task with --trace)
```

Revert "デプロイの際にcrontabファイルを更新する"

---

app/controllers/members_controller.rb
app/controllers/memberships_controller.rb
spec/controllers/members_controller_spec.rb
spec/controllers/memberships_controller_spec.rb

グループメンバーの追加と削除において権限チェックがなかった不具合を修正
- グループのメンバー追加時にログイン中ユーザーがグループの管理権限を持つことを確認するように
- グループのメンバー削除時にログイン中ユーザーがグループの管理権限を持つことを確認するように
- グループのメンバー管理の権限についてのspecを追加

グループメンバーの追加と削除においてのセキュリティ修正

---

app/controllers/annotations_controller.rb
spec/controllers/annotations_controller_spec.rb

アノテーションの追加と削除における権限の振る舞いのspecを追加
- プロジェクトのアノテーションの権限についてのspecを追加
- 作成：すべてのユーザー
- 更新：アノテーションのコラボレーターとプロジェクトのエディター・管理者
- 削除：アノテーションのコラボレーターとプロジェクトのエディター・管理者
- ステートに変換：アノテーションのコラボレーターとプロジェクトのエディター・管理者
- アノテーションについての権限がなくてもステートへの変換ができる不具合を修正

アノテーションの追加と削除においてのセキュリティ修正

---

app/controllers/states_controller.rb
spec/controllers/states_controller_spec.rb

ステートの追加と削除における権限の振る舞いのspecを追加
- プロジェクトのステートの権限についてのspecを追加
- ステートについての権限がなくてもアノテーションへの変換ができる不具合を修正

ステートの追加と削除においてのセキュリティ修正

---

app/controllers/collaborations_controller.rb
spec/controllers/collaborations_controller_spec.rb

コラボレーターの追加と削除における権限の振る舞いのspecを追加
- プロジェクトのコラボレーター管理の権限についてのspecを追加
- プロジェクトの管理権限がなくても任意のユーザーをコラボレーターに追加できる不具合を修正

コラボレーターの追加と削除についてのセキュリティ修正

---

app/controllers/note_cards_controller.rb
spec/controllers/note_cards_controller_spec.rb

メモに対しての権限のspecを追加
- プロジェクトのメモについての権限のspecを追加
- プロジェクトの権限がなくてもメモの追加、編集、削除ができる不具合を修正

メモについてのセキュリティ修正

---

spec/controllers/usages_controller_spec.rb

ユセージの権限についてのspecを拡充
- プロジェクトのユセージについての権限のspecを追加
- 作成：すべてのユーザー
- 更新：ユセージの作成者とプロジェクトのエディター・管理者
- 削除：ユセージの作成者とプロジェクトのエディター・管理者

ユセージの権限についてのspecを拡充

---

config/deploy.rb
config/deploy/production.rb
config/deploy/staging.rb

`bundle exec cap production deploy` によるデプロイの際に `cd /usr/local/rails_apps/gitfab2/releases/20201001073552 && bundle exec whenever --update-crontab -i gitfab2` を実行してcrontabファイルを更新する。
```bash
$ bundle exec  cap production deploy
$ crontab -e
0 20 * * * /bin/bash -l -c 'cd /usr/local/rails_apps/gitfab2/releases/20201001073615 && RAILS_ENV=production bundle exec rake backup:delete --silent'
30 0 * * * /bin/bash -l -c 'cd /usr/local/rails_apps/gitfab2/releases/20201001073615 && RAILS_ENV=production bundle exec rake statistic:daily --silent'
0 * * * * /bin/bash -l -c 'cd /usr/local/rails_apps/gitfab2/releases/20201001073615 && bundle exec bin/rails runner -e production '\''Rails.cache.clear'\'''
```

デプロイの際にcrontabファイルを更新する

---

app/controllers/projects_controller.rb

fabbleの「change order」で順番を変えたあと、スライド表示するとスライドの順番にchange orderが反映されない。
private projectでいくつか「Add state」をして項目を追加、その後順番を「change order」で変えた
（os osx, browser Chrome(87.0.4280.67)）、（プライベートプロジェクトで発生）
スライド表示の際に「表示順」でソートするようにした

スライド表示の際にスライド順が反映されない不具合を修正

---

config/environments/production.rb

ログレベルを `:info` から `:warn` に変更します。

プロダクション環境において重要でないログを抑制
