- app/assets/stylesheets/global_projects/index.css.scss
- app/views/global_projects/index.html.slim
> close #980 Add TOPICS

- app/assets/javascripts/recipe.js.coffee
- app/assets/stylesheets/projects/recipe.css.scss
- app/views/recipes/_recipe_cards.html.slim
> close #993 Attachment → Reference

- app/assets/javascripts/card.js.coffee
- app/assets/javascripts/project.js
- app/assets/javascripts/recipe.js.coffee
Reverts mozilla-japan/gitfab2#1027
> Revert "close #1026 make drag&dropping fancybox enable"

- app/assets/javascripts/application.js
- app/assets/javascripts/dashboard.js
- app/assets/javascripts/global_projects.js
- app/assets/javascripts/groups.js
- app/assets/javascripts/maintenance.js.coffee
- app/assets/javascripts/project.js
- app/assets/javascripts/user.js.coffee
- app/assets/stylesheets/layouts/maintence_notification.css.scss
- app/views/layouts/_maintenance_notification.html.slim
@dadaa  なるはやでdeployしたいやつなので、急ぎめだと助かります
> close #1052 show maintenance alert

- app/models/card/recipe_card.rb
- app/models/recipe.rb
サーバ上のゴミデータを消すための一時的な変更です。
このイシューに対応した修正をマージ
デプロイ
サーバでデータクリーニング
リバート
デプロイ
という感じで作業します。
> close #1060 add Card::RecipeCard class temporally

- app/models/card/transition.rb
> close #1062 add Card::Transition class temporally

- app/models/card/transition.rb
Reverts mozilla-japan/gitfab2#1063
> Revert "close #1062 add Card::Transition class temporally"

- app/models/card/recipe_card.rb
- app/models/recipe.rb
Reverts mozilla-japan/gitfab2#1065
> Revert "Revert "close #1060 add Card::RecipeCard class temporally""

- app/models/card/transition.rb
Reverts mozilla-japan/gitfab2#1064
> Revert "Revert "close #1062 add Card::Transition class temporally""

- app/assets/stylesheets/projects/basic_informations.css.scss
- app/assets/stylesheets/projects/note.css.scss
- app/assets/stylesheets/projects/note_card.css.scss
- app/views/note_cards/_note_card.html.slim
> close #1068 change style of notes/index

- app/assets/javascripts/dashboard.js
- app/assets/javascripts/features.js.coffee
- app/assets/stylesheets/dashboard.css
- app/assets/stylesheets/features/index.css.scss
- app/controllers/featured_items_controller.rb
- app/controllers/features_controller.rb
- app/controllers/notes_controller.rb
- app/models/concerns/project_owner.rb
- app/models/contribution.rb
- app/models/feature.rb
- app/models/featured_item.rb
- app/models/project.rb
- app/models/user.rb
- app/views/featured_items/_item.html.slim
- app/views/featured_items/create.json.jbuilder
- app/views/features/_feature.html.slim
- app/views/features/create.json.jbuilder
- app/views/features/index.html.slim
- app/views/projects/_basic_informations.html.slim
- config/routes.rb
> close #978 create Admin page

- app/views/components/_card_description.html.slim
- app/views/note_cards/_note_card.html.slim
- app/views/note_cards/show.html.slim
Reverts mozilla-japan/gitfab2#1072
> Revert "close #1071 change Sanitize option of note#show"

- app/assets/javascripts/global_project.js.coffee
- app/assets/stylesheets/global_projects/index.css.scss
- app/views/global_projects/_functions.html.slim
- app/views/global_projects/_occasions.html.slim
- app/views/global_projects/index.html.slim
[![Gyazo](http://i.gyazo.com/ccbfd93cbbac65e409ca97c71436db21.gif)](http://gyazo.com/ccbfd93cbbac65e409ca97c71436db21)
> close #1095 Top page in Japanese

- app/assets/javascripts/slideshow.coffee
- app/assets/stylesheets/projects/slideshow.css.scss
[![Gyazo](http://i.gyazo.com/9555024ff976168a956e5667e020c48a.gif)](http://gyazo.com/9555024ff976168a956e5667e020c48a)
> close #1115 Revise Slideshow View

- app/assets/javascripts/basic_informations.js.coffee
> close #1128 Fork duplication

- app/assets/javascripts/features.js.coffee
- app/models/project.rb
- app/views/features/_feature.html.slim
Featured Project, User, Groupのセレクトボックスで検索できるように
> close #1150 revise admin page

- app/controllers/annotations_controller.rb
#1225 クローズするためのプルリクエスト。元のメソッドを二つに分割して、条件に合わせて使い分けるように変更
> close #1225 revise AnntionsController#update_contribution

- app/controllers/global_projects_controller.rb
- app/models/project.rb
Work In Progressです。
sunspotの ```order_by``` が動かないので、ここを回避するWorkaroundが必要。
https://github.com/sunspot/sunspot/wiki/Ordering-and-pagination
> WIP #1305 fix page transition in search result.

- app/assets/stylesheets/layouts/_footer.css.scss
- app/assets/stylesheets/mixins/variables.css.scss
- app/views/layouts/_footer.html.slim
- app/views/static_pages/privacy.html.slim
- app/views/static_pages/terms.html.slim
> close #1279 change privacy policy and terms

- app/controllers/global_projects_controller.rb
- app/models/project.rb
Reverts mozilla-japan/gitfab2#1306
> Revert "WIP #1305 fix page transition in search result."

- app/controllers/api/v0/annotations_controller.rb
- app/controllers/api/v0/projects_controller.rb
- app/controllers/api/v0/states_controller.rb
- app/views/api/v0/annotations/index.json.jbuilder
- app/views/api/v0/annotations/show.json.jbuilder
- app/views/api/v0/projects/index.json.jbuilder
- app/views/api/v0/projects/show.json.jbuilder
- app/views/api/v0/states/index.json.jbuilder
- app/views/api/v0/states/show.json.jbuilder
下記２点ご相談案件です。
* URLに何を含めるべきかが
いまのところ、それぞれのアクションで個々のリソースは
* index：一階層上のリソースのURL + 一階層下のリソース
* show：複数階層の上のリソース+一階層下のリソース
を持っているんですが、showには同じ階層の次とか前のリソースのURL入れたほうがよいですかね
* description をSanitizeしちゃってる部分
いまのところ特に使うことないかと思ったのでテキストだけ返すようにしてるのですが、HTMLタグ含めるのとどっちがいいでしょう
> close #1353 change API data

- app/assets/javascripts/maintenance.js.coffee
Reverts mozilla-japan/gitfab2#1375
> Revert "close #1374 show maintenance alert"

- config/environments/production.rb
Reverts mozilla-japan/gitfab2#1380
> Revert "close #1377 for ssl"

- app/assets/javascripts/basic_informations.js.coffee
- app/assets/javascripts/project.js
- app/assets/stylesheets/projects/basic_informations.css.scss
- app/assets/stylesheets/projects/relation_tree.css.scss
- app/controllers/global_projects_controller.rb
- app/controllers/projects_controller.rb
- app/models/ability.rb
- app/models/project.rb
- app/views/layouts/project.html.slim
- app/views/projects/_relations.html.slim
- app/views/projects/relation_tree.json.jbuilder
- config/routes.rb
- vendor/assets/javascripts/d3.js
> Sclose #1312 Rendering Projects relation tree

- config/deploy.rb
Reverts mozilla-japan/gitfab2#1438
> Revert "hotfix for deploy"

- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/users/edit.html.slim
次の問題に対する応急処置
- ユーザー名を変更することでslugが変更される
- ユーザーのslugで関連を持っている箇所の関連が切れる（Comment#user_id）
> ユーザー名の変更を禁止

- config/deploy/production.rb
デプロイ時に`shared/config/secrets.yml`を配置する
> config/secrets.yml のデプロイ設定を追加

- config/deploy/production.rb
> Revert "config/secrets.yml のデプロイ設定を追加"

- app/assets/stylesheets/global_projects/index.css.scss
- app/views/global_projects/index.html.slim
| before | after |
| ------- | ----- |
| ![image](https://user-images.githubusercontent.com/60980/34934496-03dcc12a-fa1e-11e7-9bd6-9d74e9101570.png) | ![image](https://user-images.githubusercontent.com/60980/34934542-3153179e-fa1e-11e7-9034-8f5e12eb5c00.png) |
> 上部のお知らせ欄を撤去

- app/assets/stylesheets/layouts/_footer.scss
- app/views/components/_card_form.html.slim
- app/views/layouts/_footer.html.slim
> Hotfix tokiwatch gitfab2 #1 and #2

- app/assets/javascripts/card_order.js
See https://github.com/takeyuwebinc/gitfab2/pull/102
> Fix changing the order of annotations

- app/assets/stylesheets/projects/index.scss
- app/views/projects/index.html.slim
- 画像を横いっぱいに表示
- メッセージの後ろにグレーを敷いて、文字が常に立つように変更
> トップ画像のハンドリングの変更

- app/uploaders/attachment_uploader.rb
STLをアップロードしようとしたときにエラーが発生した不具合を修正
> Fix thumbnail creation error

- README.md
- app/assets/stylesheets/projects/index.scss
- app/views/layouts/_header.html.slim
fab3dコンテスト告知用のtickerを表示するようにした。
あとで、変数で処理できるようにする。
> fab3dコンテスト向けのアップデート

- app/models/project_access_log.rb
- app/views/projects/_tags.html.slim
- app/views/projects/_tags_and_keywords.html.slim
- app/views/tags/_tag.html.slim
- spec/models/project_access_log_spec.rb
- spec/spec_helper.rb
Fix https://github.com/takeyuwebinc/gitfab2/issues/103
> 検索文字列に `#` があるとき検索できない問題を修正

- Gemfile
- Gemfile.lock
- config/scout_apm.yml
ScoutAPM
https://scoutapm.com
有効にするには環境変数の設定が必要
```bash
export SCOUT_KEY=YOURKEY
```
https://docs.scoutapm.com/#ruby-env-vars
> Enable application performance monitoring

- app/controllers/projects_controller.rb
- app/models/card/annotation.rb
- app/models/card/state.rb
- app/views/components/_card_comments.html.slim
- app/views/components/_card_description.html.slim
- app/views/components/_card_figures.html.slim
- app/views/projects/_recipe_cards.html.slim
- app/views/projects/_usages.html.slim
- app/views/states/_state.html.slim
| before | after |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/60980/90684950-fb301380-e2a3-11ea-894c-c5154d489cfa.png) | ![image](https://user-images.githubusercontent.com/60980/90684253-d7b89900-e2a2-11ea-9072-c27bbdfed7e1.png) |
> 詳細ページのN+1クエリを殺す
